/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Chips: typeof import('primevue/chips')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('./src/components/layout/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    TaskCalendar: typeof import('./src/components/tasks/TaskCalendar.vue')['default']
    TaskForm: typeof import('./src/components/tasks/TaskForm.vue')['default']
    TaskList: typeof import('./src/components/tasks/TaskList.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
